

CREATE TABLE public.usuario (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                cpf varchar(255) NULL,
                                data_nascimento date NULL,
                                email varchar(255) NULL,
                                nome varchar(255) NULL,
                                "password" varchar(255) NULL,
                                "role" varchar(255) NULL,
                                status_usuario varchar(255) NULL,
                                CONSTRAINT usuario_pkey PRIMARY KEY (id),
                                CONSTRAINT usuario_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[]))),
	CONSTRAINT usuario_status_usuario_check CHECK (((status_usuario)::text = ANY ((ARRAY['ATIVO'::character varying, 'PENDENTE'::character varying, 'BLOQUEADO'::character varying, 'DESATIVADO'::character varying])::text[])))
);

INSERT INTO public.usuario
(id, cpf, data_nascimento, email, nome, "password", "role", status_usuario)
VALUES(1, '01421501503', '1994-04-06', 'ruantarciisio@admin.com', 'Ruan Tarcisio', '$2a$12$JW/ieheYP35Fx1zcxA40Ae7wmD03lGb9LNKCw7Rpo2OQ3nrjEXMFK', 'ADMIN', 'ATIVO');
