BEGIN;

-- CREATE TABLE usuario (
--                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                          nome VARCHAR(255),
--                          email VARCHAR(255) UNIQUE,
--                          password VARCHAR(255),
--                          cpf VARCHAR(20) UNIQUE,
--                          data_nascimento DATE,
--                          role VARCHAR(255) CHECK (role IN ('ADMIN', 'USER')),
--                          status_usuario VARCHAR(255) CHECK (status_usuario IN ('ATIVO', 'PENDENTE', 'BLOQUEADO', 'DESATIVADO'))
-- );
--
--
-- CREATE TABLE usuario_country (
--                                  usuario_id BIGINT NOT NULL,
--                                  country_id BIGINT NOT NULL,
--                                  PRIMARY KEY (usuario_id, country_id),
--                                  FOREIGN KEY (usuario_id) REFERENCES usuario(id),
--                                  FOREIGN KEY (country_id) REFERENCES country(id)
-- );
--
--
INSERT INTO public.usuario
(id, cpf, data_nascimento, email, nome, "password", "role", status_usuario)
VALUES(1, '01421501503', '1994-04-06', 'ruantarciisio@admin.com', 'Ruan Tarcisio', '$2a$12$JW/ieheYP35Fx1zcxA40Ae7wmD03lGb9LNKCw7Rpo2OQ3nrjEXMFK', 'ADMIN', 'ATIVO');

INSERT INTO public.usuario
(id, cpf, data_nascimento, email, nome, "password", "role", status_usuario)
VALUES(2, '01234567890', '2000-11-06', 'sarah@admin.com', 'Sarah', '$2a$12$JW/ieheYP35Fx1zcxA40Ae7wmD03lGb9LNKCw7Rpo2OQ3nrjEXMFK', 'ADMIN', 'ATIVO');


INSERT INTO usuario_country (usuario_id, country_id) VALUES (1, 1);
INSERT INTO usuario_country (usuario_id, country_id) VALUES (1, 2);


--
-- CREATE TABLE usuario (
--                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                          nome VARCHAR(255),
--                          email VARCHAR(255) UNIQUE,
--                          password VARCHAR(255),
--                          cpf VARCHAR(20) UNIQUE,
--                          data_nascimento DATE,
--                          status_usuario VARCHAR(255) CHECK (status_usuario IN ('ATIVO', 'PENDENTE', 'BLOQUEADO', 'DESATIVADO')),
--                          role VARCHAR(255) CHECK (role IN ('ADMIN', 'USER'))
-- );
--
-- CREATE TABLE country (
--                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                          code VARCHAR(255),
--                          name VARCHAR(255)
-- );
--
-- CREATE TABLE usuario_country (
--                                  usuario_id BIGINT NOT NULL,
--                                  country_id BIGINT NOT NULL,
--                                  PRIMARY KEY (usuario_id, country_id),
--                                  FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
--                                  FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE
-- );
--

COMMIT;