-- Criação da tabela country
CREATE TABLE country (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         code VARCHAR(255),
                         name VARCHAR(255),
                         PRIMARY KEY (id)
);

-- Criação da tabela sport
CREATE TABLE sport (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       description_sport VARCHAR(255),
                       name_sport VARCHAR(255),
                       qtd_participants INTEGER,
                       PRIMARY KEY (id)
);

-- Criação da tabela medal_bronze
CREATE TABLE medal_bronze (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              award_date DATE NOT NULL,
                              country_id BIGINT,
                              sport_id BIGINT,
                              FOREIGN KEY (country_id) REFERENCES public.country (id),
                              FOREIGN KEY (sport_id) REFERENCES public.sport (id)
);

-- Criação da tabela medal_gold
CREATE TABLE medal_gold (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            award_date DATE NOT NULL,
                            country_id BIGINT,
                            sport_id BIGINT,
                            FOREIGN KEY (country_id) REFERENCES public.country (id),
                            FOREIGN KEY (sport_id) REFERENCES public.sport (id)
);

-- Criação da tabela medal_silver
CREATE TABLE medal_silver (

                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              award_date DATE NOT NULL,
                              country_id BIGINT,
                              sport_id BIGINT,
                              FOREIGN KEY (country_id) REFERENCES public.country (id),
                              FOREIGN KEY (sport_id) REFERENCES public.sport (id)
);