BEGIN;

INSERT INTO public.sport (id, description_sport, name_sport, qtd_participants)
VALUES
    (1, 'Atletismo, incluindo corridas, saltos e arremessos.', 'Atletismo', 1),
    (2, 'Competições de natação incluindo livre, costas, peito e borboleta.', 'Natação', 1),
    (3, 'Ginástica artística envolvendo exercícios de solo, salto, barras assimétricas e trave de equilíbrio.', 'Ginástica Artística', 1),
    (4, 'Ginástica rítmica envolvendo apresentações com fita, arco, bola e maças.', 'Ginástica Rítmica', 1),
    (5, 'Levantamento de peso com diferentes categorias de peso.', 'Levantamento de Peso', 1),
    (6, 'Luta com competições no estilo livre e Greco-romano.', 'Luta', 1),
    (7, 'Boxe com diferentes categorias de peso.', 'Boxe', 1),
    (8, 'Esgrima com competições de florete, épée e sabre.', 'Esgrima', 1),
    (9, 'Judô com competições em diferentes categorias de peso e técnicas.', 'Judô', 1),
    (10, 'Taekwondo com combates focados em técnicas de golpe.', 'Taekwondo', 1),
    (11, 'Tiro com arco incluindo competições individuais e por equipes.', 'Tiro com Arco', 1),
    (12, 'Esportes aquáticos incluindo natação, saltos ornamentais, nado sincronizado e maratona aquática.', 'Esportes Aquáticos', 1),
    (13, 'Ciclismo com competições de estrada, pista, BMX e mountain bike.', 'Ciclismo', 1),
    (14, 'Futebol (soccer) com partidas em equipe.', 'Futebol', 11),
    (15, 'Handebol com partidas em equipe e pontuação com uma bola.', 'Handebol', 7),
    (16, 'Basquete com partidas em equipe e pontuação com uma cesta.', 'Basquete', 5),
    (17, 'Voleibol de quadra com partidas em equipe e pontuação com uma bola sobre a rede.', 'Voleibol', 6),
    (18, 'Voleibol de praia com partidas em equipe em quadras de areia.', 'Voleibol de Praia', 2),
    (19, 'Tênis com partidas individuais e em duplas.', 'Tênis', 2),
    (20, 'Tênis de mesa com partidas individuais e em duplas.', 'Tênis de Mesa', 2),
    (21, 'Badminton com partidas individuais e em duplas.', 'Badminton', 2),
    (22, 'Golfe com torneios individuais e por equipes.', 'Golfe', 1),
    (23, 'Surfe em ondas oceânicas.', 'Surfe', 1),
    (24, 'Escalada esportiva incluindo escalada de dificuldade, boulder e velocidade.', 'Escalada Esportiva', 1),
    (25, 'Skateboarding com competições de street e park.', 'Skateboarding', 1),
    (26, 'Rugby Sevens com partidas em equipe de sete jogadores.', 'Rugby Sevens', 7),
    (27, 'Canoagem com competições de velocidade e slalom.', 'Canoagem', 1),
    (28, 'Remo com competições em diferentes categorias de barco e distâncias.', 'Remo', 1),
    (29, 'Vela com corridas em diferentes classes de barco.', 'Vela', 1),
    (30, 'Pentatlo Moderno incluindo esgrima, natação, equitação, corrida e tiro.', 'Pentatlo Moderno', 1),
    (31, 'Breaking (ou breakdancing) com competições individuais e em grupo.', 'Breaking', 1),
    (32, 'Patinação artística com apresentações.', 'Patinação Artística', 1),
    (33, 'Arremesso de peso, lançamento de dardo e lançamento de disco.', 'Atletismo - Campo', 1),
    (34, 'Competições de natação em águas abertas.', 'Natação em Águas Abertas', 1),
    (35, 'Competições de esgrima de combate.', 'Esgrima de Combate', 1),
    (36, 'Competições de tiro ao alvo.', 'Tiro ao Alvo', 1),
    (37, 'Competições de ciclismo em pista coberta.', 'Ciclismo em Pista', 1),
    (38, 'Competições de atletismo em pista coberta.', 'Atletismo em Pista Coberta', 1),
    (39, 'Competições de escalada em rocha.', 'Escalada em Rocha', 1),
    (40, 'Competições de patinação no gelo.', 'Patinação no Gelo', 1),
    (41, 'Competições de curling.', 'Curling', 1),
    (42, 'Competições de hockey no gelo.', 'Hockey no Gelo', 1),
    (43, 'Competições de esqui alpino.', 'Esqui Alpino', 1),
    (44, 'Competições de esqui cross-country.', 'Esqui Cross-Country', 1),
    (45, 'Competições de snowboard.', 'Snowboard', 1);

INSERT INTO public.country (id, code, "name")
VALUES
    (1, 'USA', 'United States'),
    (2, 'BRA', 'Brazil'),
    (3, 'CHN', 'China'),
    (4, 'JPN', 'Japan'),
    (5, 'GER', 'Germany'),
    (6, 'FRA', 'France'),
    (7, 'GBR', 'Great Britain'),
    (8, 'RUS', 'Russia'),
    (9, 'ITA', 'Italy'),
    (10, 'CAN', 'Canada'),
    (11, 'AUS', 'Australia'),
    (12, 'KOR', 'South Korea'),
    (13, 'NED', 'Netherlands'),
    (14, 'HUN', 'Hungary'),
    (15, 'ESP', 'Spain'),
    (16, 'KEN', 'Kenya'),
    (17, 'JAM', 'Jamaica'),
    (18, 'SWE', 'Sweden'),
    (19, 'CUB', 'Cuba'),
    (20, 'NZL', 'New Zealand'),
    (21, 'UZB', 'Uzbekistan'),
    (22, 'KAZ', 'Kazakhstan'),
    (23, 'COL', 'Colombia'),
    (24, 'SWI', 'Switzerland'),
    (25, 'NOR', 'Norway'),
    (26, 'BEL', 'Belgium'),
    (27, 'THA', 'Thailand'),
    (28, 'AZE', 'Azerbaijan'),
    (29, 'POL', 'Poland'),
    (30, 'IRI', 'Iran'),
    (31, 'GRE', 'Greece'),
    (32, 'ARG', 'Argentina'),
    (33, 'DEN', 'Denmark'),
    (34, 'CZE', 'Czech Republic'),
    (35, 'ETH', 'Ethiopia'),
    (36, 'FIN', 'Finland'),
    (37, 'POR', 'Portugal'),
    (38, 'TUR', 'Turkey'),
    (39, 'TUN', 'Tunisia'),
    (40, 'DOM', 'Dominican Republic'),
    (41, 'IRL', 'Ireland'),
    (42, 'ISR', 'Israel'),
    (43, 'BUL', 'Bulgaria'),
    (44, 'TPE', 'Chinese Taipei'),
    (45, 'SRB', 'Serbia'),
    (46, 'MEX', 'Mexico'),
    (47, 'BLR', 'Belarus'),
    (48, 'SVK', 'Slovakia'),
    (49, 'GEO', 'Georgia'),
    (50, 'SLO', 'Slovenia');

COMMIT;